### ISSUE TITLE
登入进入到首页之后,左侧的菜单不显示

### ISSUE THREAD

**Issue by pandaOreo** [moell-peng/mojito-admin#3]
<img width="1945" alt="image" src="https://user-images.githubusercontent.com/35425100/156689042-f7e615e7-fd05-4d26-ba2f-de4abd376156.png">

**Comment by moell-peng** [comment]
执行了 php artisan db:seed --class="Moell\Mojito\Database\MojitoTableSeeder" 命令了吗？检查以下数据库中是否存在数据。@pandaOreo

**Comment by pandaOreo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by pandaOreo** [comment]
知道问题了,是因为icon的问题,menu表里面的icon删掉就可以显示了,还有默认生成的uri好像和教程上的初始化不一样,得把/admin删掉才能正确访问
<img width="467" alt="image" src="https://user-images.githubusercontent.com/35425100/156695452-d1e936ca-f499-41ff-a48f-23338cb90600.png">
@moell-peng

**Comment by moell-peng** [comment]
@pandaOreo 多谢反馈， 下个版本会修复这个问题来跟进前端模板的更新，如果想使用Icon填写Element Plus 的Svg Icon即可。

**Comment by moell-peng** [comment]
@pandaOreo 已修复

**Comment by pandaOreo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
